const VOCABULARY_DATABASE = [
    {
        id: "master-guide",
        category: "Master Guide",
        icon: "📖",
        isGuide: true,
        description: "Everything you need to know about learning vocabulary effectively.",
        content: {
            definition: "Vocabulary means all the words of a language that we understand and use.",
            benefits: [
                "Speak confidently in any situation",
                "Write clearly and professionally",
                "Understand English movies and books faster",
                "Score better in competitive exams",
                "Express complex emotions properly"
            ],
            whatIsVocab: [
                { label: "Meaning", desc: "Knowing what the word represents." },
                { label: "Usage", desc: "Knowing how the word fits in a sentence." },
                { label: "Grammar Role", desc: "Knowing if it's a noun, verb, etc." },
                { label: "Context", desc: "Knowing when and where to use it." }
            ],
            mainCategories: ["Nouns (Naming)", "Verbs (Action)", "Adjectives (Describing)", "Adverbs (Manner)"],
            nounCategories: [
                { title: "People", words: ["student", "teacher", "doctor", "engineer", "friend", "leader", "manager", "customer", "employee", "neighbor"], example: "The teacher helps every student." },
                { title: "Places", words: ["school", "college", "office", "hospital", "market", "station", "restaurant", "library", "city", "village"], example: "She works in an office." },
                { title: "Things", words: ["book", "pen", "phone", "computer", "table", "chair", "bag", "car", "bottle", "clock"], example: "Keep the book on the table." },
                { title: "Abstract Ideas", words: ["success", "failure", "confidence", "freedom", "knowledge", "experience", "pressure", "happiness", "responsibility", "opportunity"], example: "Hard work brings success." }
            ],
            verbCategories: [
                { title: "Basic Verbs", words: ["go", "come", "eat", "drink", "sleep", "walk", "run", "sit", "stand", "talk", "listen", "read", "write", "open", "close"], example: "I read every day." },
                { title: "Professional Verbs", words: ["achieve", "manage", "develop", "improve", "create", "solve", "handle", "organize", "maintain", "reduce"], example: "She achieved her goals." },
                { title: "Thinking & Feeling", words: ["think", "believe", "understand", "remember", "forget", "imagine", "feel", "realize", "decide"], example: "I understand the lesson." }
            ],
            adjectives: [
                { title: "Size", words: ["big", "small", "huge", "tiny"] },
                { title: "Quality", words: ["good", "bad", "excellent", "poor"] },
                { title: "Emotion", words: ["happy", "sad", "angry", "excited"] },
                { title: "Personality", words: ["honest", "lazy", "hardworking", "kind", "polite", "rude", "brave", "patient", "confident", "shy"], example: "He is a hardworking student." }
            ],
            adverbs: ["quickly", "slowly", "carefully", "clearly", "always", "never", "sometimes", "here", "there"],
            dailyWords: ["actually", "basically", "probably", "sure", "maybe", "okay", "exactly", "already", "finally", "seriously"],
            emotionWords: ["excited", "nervous", "worried", "relaxed", "proud", "lonely", "frustrated", "surprised", "confused", "hopeful"],
            academicVocab: ["benefit", "advantage", "disadvantage", "impact", "cause", "effect", "solution", "process", "result", "analysis", "conclusion", "evidence", "factor", "method"],
            transitionWords: ["because", "however", "therefore", "although", "moreover", "meanwhile", "for example", "in addition", "finally", "in conclusion"],
            synonyms: [
                { w1: "happy", w2: "joyful" }, { w1: "big", w2: "huge" }, { w1: "small", w2: "tiny" },
                { w1: "fast", w2: "quick" }, { w1: "angry", w2: "furious" }, { w1: "good", w2: "excellent" }, { w1: "bad", w2: "terrible" }
            ],
            antonyms: [
                { w1: "hot", w2: "cold" }, { w1: "rich", w2: "poor" }, { w1: "easy", w2: "difficult" },
                { w1: "early", w2: "late" }, { w1: "strong", w2: "weak" }, { w1: "success", w2: "failure" }
            ],
            wordFamilies: [
                { v: "educate", n: "education", a: "educated" },
                { v: "beautify", n: "beauty", a: "beautiful", adv: "beautifully" },
                { v: "succeed", n: "success", a: "successful", adv: "successfully" }
            ],
            phrasalVerbs: [
                { v: "give up", m: "stop trying" }, { v: "look after", m: "take care" }, { v: "find out", m: "discover" },
                { v: "pick up", m: "collect" }, { v: "carry on", m: "continue" }, { v: "turn on", m: "start" },
                { v: "turn off", m: "stop" }, { v: "run out", m: "finish" }
            ],
            collocations: ["make decision", "take rest", "do homework", "heavy rain", "strong coffee", "fast food", "pay attention"],
            commonErrors: [
                { wrong: "informations", right: "information" },
                { wrong: "discuss about", right: "discuss" },
                { wrong: "very much happy", right: "very happy" },
                { wrong: "equipments", right: "equipment" }
            ],
            learningMethod: {
                daily: "Learn 10 words (5 nouns, 3 verbs, 2 adjectives)",
                steps: ["Read word", "Learn meaning", "Make sentence", "Find synonym", "Speak it aloud"],
                rule: "Write → Speak → Repeat → Use"
            },
            practice: {
                word: "Confidence",
                sentence: "I speak English with confidence.",
                synonym: "belief",
                opposite: "fear"
            }
        }
    },
    {
        id: "daily-verbs",
        category: "Essential Verbs",
        icon: "🏃",
        description: "Must-know action words for everyday communication.",
        words: [
            { word: "Achieve", phonetic: "/əˈtʃiːv/", meaning: "To successfully finish or do something.", hindi: "हासिल करना", examples: ["She worked hard to achieve her goals.", "He achieved high marks in the exam."], synonyms: ["Attain", "Accomplish"], antonyms: ["Fail", "Abandon"] },
            { word: "Believe", phonetic: "/bɪˈliːv/", meaning: "To think that something is true.", hindi: "विश्वास करना", examples: ["You should believe in yourself.", "I believe we can win."], synonyms: ["Trust", "Accept"], antonyms: ["Doubt", "Deny"] },
            { word: "Communicate", phonetic: "/kəˈmjuːnɪkeɪt/", meaning: "To share information with others.", hindi: "संवाद करना", examples: ["We need to communicate more effectively.", "They communicate via email."], synonyms: ["Convey", "Interact"] },
            { word: "Describe", phonetic: "/dɪˈskraɪb/", meaning: "To say what something is like.", hindi: "वर्णन करना", examples: ["Can you describe the person you saw?", "She described her trip in detail."], synonyms: ["Explain", "Portray"] },
            { word: "Explain", phonetic: "/ɪkˈspleɪn/", meaning: "To make something clear or easy to understand.", hindi: "समझाना", examples: ["Please explain this rule to me.", "The teacher explained the lesson."], synonyms: ["Clarify", "Elucidate"], antonyms: ["Confuse", "Obscure"] },
            { word: "Analyze", phonetic: "/ˈænəlaɪz/", meaning: "To examine something in detail.", hindi: "विश्लेषण करना", examples: ["We need to analyze the data first.", "She analyzed the poem in class."], synonyms: ["Examine", "Inspect"] },
            { word: "Compare", phonetic: "/kəmˈpeə(r)/", meaning: "To look at two things to see how they are similar.", hindi: "तुलना करना", examples: ["Don't compare yourself with others.", "Compare these two products before buying."], synonyms: ["Contrast", "Match"] },
            { word: "Create", phonetic: "/kriˈeɪt/", meaning: "To bring something new into existence.", hindi: "बनाना / सृजन करना", examples: ["He wants to create a new app.", "Music creates a relaxing atmosphere."], synonyms: ["Produce", "Generate"], antonyms: ["Destroy", "Demolish"] },
            { word: "Develop", phonetic: "/dɪˈveləp/", meaning: "To grow or cause to grow and become more mature.", hindi: "विकसित करना", examples: ["They are developing new software.", "Exercise helps develop muscles."] },
            { word: "Evaluate", phonetic: "/ɪˈvæljueɪt/", meaning: "To judge the value or quality of something.", hindi: "मूल्यांकन करना", examples: ["We must evaluate the results.", "Teachers evaluate students' performance."] },
            { word: "Focus", phonetic: "/ˈfəʊkəs/", meaning: "To give all your attention to something.", hindi: "ध्यान केंद्रित करना", examples: ["Focus on your studies.", "He focused the camera on the bird."] },
            { word: "Generate", phonetic: "/ˈdʒenəreɪt/", meaning: "To produce or create something.", hindi: "उत्पन्न करना", examples: ["The wind turbines generate electricity.", "The ad generated a lot of interest."] },
            { word: "Handle", phonetic: "/ˈhændl/", meaning: "To manage or deal with a situation.", hindi: "संभालना", examples: ["Can you handle this project?", "She handles pressure very well."] },
            { word: "Identify", phonetic: "/aɪˈdentɪfaɪ/", meaning: "To recognize who or what someone or something is.", hindi: " पहचानना", examples: ["Can you identify this plant?", "The witness identified the suspect."] },
            { word: "Improve", phonetic: "/ɪmˈpruːv/", meaning: "To make something better.", hindi: "सुधारना", examples: ["I want to improve my English.", "His health is improving."] },
            { word: "Justify", phonetic: "/ˈdʒʌstɪfaɪ/", meaning: "To show or prove to be right.", hindi: "औचित्य सिद्ध करना", examples: ["How can you justify your actions?", "The results justify the cost."] },
            { word: "Know", phonetic: "/nəʊ/", meaning: "To have information or knowledge.", hindi: "जानना", examples: ["I know the answer.", "Do you know where he lives?"] },
            { word: "Lead", phonetic: "/liːd/", meaning: "To show the way or be in charge.", hindi: "नेतृत्व करना", examples: ["Who will lead the team?", "All roads lead to the city center."] },
            { word: "Manage", phonetic: "/ˈmænɪdʒ/", meaning: "To be in charge of or organized.", hindi: "प्रबंध करना", examples: ["She manages a small team.", "I managed to finish on time."] },
            { word: "Negotiate", phonetic: "/nɪˈɡəʊʃieɪt/", meaning: "To try to reach an agreement.", hindi: "मोलभाव करना", examples: ["We need to negotiate a better deal.", "She is good at negotiating."] },
            { word: "Observe", phonetic: "/əbˈzɜːv/", meaning: "To watch carefully.", hindi: "निरीक्षण करना", examples: ["Scientists observe the stars.", "Observe the rules of the road."] },
            { word: "Participate", phonetic: "/pɑːˈtɪsɪpeɪt/", meaning: "To take part in an activity.", hindi: "भाग लेना", examples: ["Everyone should participate in the discussion.", "She participated in the marathon."] },
            { word: "Question", phonetic: "/ˈkwestʃən/", meaning: "To ask for information.", hindi: "सवाल करना", examples: ["Don't be afraid to question things.", "The police questioned him for hours."] },
            { word: "Recommend", phonetic: "/ˌrekəˈmend/", meaning: "To suggest something as good.", hindi: "सिफारिश करना", examples: ["I recommend this book.", "What would you recommend for lunch?"] },
            { word: "Solve", phonetic: "/sɒlv/", meaning: "To find an answer to a problem.", hindi: "हल करना", examples: ["She solved the math problem.", "Help us solve this mystery."] }
        ]
    },
    {
        id: "emotions",
        category: "Feeling & Emotions",
        icon: "🎭",
        description: "Words to express your thoughts and feelings clearly.",
        words: [
            { word: "Anxious", phonetic: "/ˈæŋkʃəs/", meaning: "Feeling worried or nervous.", hindi: "चिंतित", examples: ["I feel anxious about the presentation.", "People are anxious for news."] },
            { word: "Confident", phonetic: "/ˈkɒnfɪdənt/", meaning: "Feeling sure about one's own abilities.", hindi: "आत्मविश्वासी", examples: ["She is a very confident speaker.", "I feel confident about the result."] },
            { word: "Enthusiastic", phonetic: "/ɪnˌθjuːziˈæstɪk/", meaning: "Showing intense enjoyment or interest.", hindi: "उत्साही", examples: ["The team was enthusiastic about the project.", "She gave an enthusiastic performance."] },
            { word: "Grateful", phonetic: "/ˈɡreɪtfʊl/", meaning: "Feeling or showing appreciation for kindness.", hindi: "आभारी", examples: ["I am grateful for your help.", "She was grateful for the opportunity."] },
            { word: "Overwhelmed", phonetic: "/ˌəʊvəˈwelmd/", meaning: "Defeated by a huge amount of something.", hindi: "अभिभूत", examples: ["I felt overwhelmed by the work.", "The response was overwhelming."] },
            { word: "Baffled", phonetic: "/ˈbæfld/", meaning: "Totally confused; bewildered.", hindi: "व्याकुल / चकित", examples: ["I am baffled by his behavior.", "The puzzles left us completely baffled."] },
            { word: "Content", phonetic: "/kənˈtent/", meaning: "In a state of peaceful happiness.", hindi: "संतुष्ट", examples: ["She is content with her simple life.", "He sat back with a content smile."] },
            { word: "Disappointed", phonetic: "/ˌdɪsəˈpɔɪntɪd/", meaning: "Sad because something failed.", hindi: "निराश", examples: ["I was disappointed by the movie.", "They were disappointed with the service."] },
            { word: "Ecstatic", phonetic: "/ɪkˈstætɪk/", meaning: "Feeling great enthusiasm or happiness.", hindi: "अति प्रसन्न", examples: ["She was ecstatic about the news.", "The crowd was ecstatic after the win."] },
            { word: "Frustrated", phonetic: "/frʌˈstreɪtɪd/", meaning: "Feeling annoyed or less confident.", hindi: "कुंठित / हताश", examples: ["I feel frustrated with my progress.", "She was frustrated by the delays."] },
            { word: "Gloomy", phonetic: "/ˈɡluːmi/", meaning: "Feeling sad and without hope.", hindi: "उदास", examples: ["He was in a gloomy mood.", "The future looks gloomy."] },
            { word: "Hopeful", phonetic: "/ˈhəʊpfl/", meaning: "Feeling or inspiring optimism.", hindi: "आशावादी", examples: ["I am hopeful about the future.", "She gave me a hopeful look."] },
            { word: "Irritated", phonetic: "/ˈɪrɪteɪtɪd/", meaning: "Slightly angry; annoyed.", hindi: "चिड़चिड़ा", examples: ["She was irritated by the noise.", "He spoke in an irritated voice."] },
            { word: "Joyful", phonetic: "/ˈdʒɔɪfl/", meaning: "Feeling, expressing, or causing great pleasure.", hindi: "हर्षपूर्ण", examples: ["It was a joyful occasion.", "Children have joyful faces."] },
            { word: "Keen", phonetic: "/kiːn/", meaning: "Highly developed; sharp.", hindi: "उत्सुक", examples: ["He is keen to start the project.", "A keen sense of smell."] },
            { word: "Lonely", phonetic: "/ˈləʊnli/", meaning: "Sad because one has no friends or company.", hindi: "अकेला", examples: ["Living alone can be lonely.", "She felt lonely in the big city."] },
            { word: "Melancholic", phonetic: "/ˌmelənˈkɒlɪk/", meaning: "Feeling soft or gentle sadness.", hindi: "उदास / विषादग्रस्त", examples: ["He was in a melancholic mood.", "A melancholic piece of music."] },
            { word: "Nervous", phonetic: "/ˈnɜːvəs/", meaning: "Easily agitated or alarmed.", hindi: "घबराया हुआ", examples: ["I feel nervous before interviews.", "She has a nervous habit of biting nails."] },
            { word: "Optimistic", phonetic: "/ˌɒptɪˈmɪstɪk/", meaning: "Hopeful and confident about the future.", hindi: "आशावादी", examples: ["She is optimistic about the outcome.", "Take an optimistic view of life."] },
            { word: "Pessimistic", phonetic: "/ˌpesɪˈmɪstɪk/", meaning: "Tending to see the worst aspect of things.", hindi: "निराशावादी", examples: ["Don't be so pessimistic.", "He has a pessimistic attitude."] },
            { word: "Restless", phonetic: "/ˈrestləs/", meaning: "Unable to rest or relax.", hindi: "बेचैन", examples: ["He had a restless night.", "The kids are getting restless."] },
            { word: "Satisfied", phonetic: "/ˈsætɪsfaɪd/", meaning: "Contented; pleased.", hindi: "संतुष्ट", examples: ["Are you satisfied with the work?", "She gave a satisfied sigh."] },
            { word: "Thrilled", phonetic: "/θrɪld/", meaning: "Excited and happy.", hindi: "रोमांचित", examples: ["I was thrilled to meet him.", "She was thrilled with the gift."] },
            { word: "Uneasy", phonetic: "/ʌnˈiːzi/", meaning: "Causing or feeling anxiety; troubled.", hindi: "बेचैन / असहज", examples: ["She felt uneasy about the plan.", "An uneasy silence followed."] },
            { word: "Worried", phonetic: "/ˈwʌrid/", meaning: "Anxious or troubled about problems.", hindi: "चिंतित", examples: ["I'm worried about my exams.", "She had a worried expression."] }
        ]
    },
    {
        id: "travel",
        category: "Travel & Tourism",
        icon: "✈️",
        description: "Essential vocabulary for your next adventure.",
        words: [
            { word: "Accommodation", phonetic: "/əˌkɒməˈdeɪʃn/", meaning: "A place to live or stay.", hindi: "आवास", examples: ["The hotel provides excellent accommodation.", "We're looking for cheap accommodation."] },
            { word: "Destination", phonetic: "/ˌdestɪˈneɪʃn/", meaning: "The place to which someone is going.", hindi: "गंतव्य", examples: ["Paris is a popular tourist destination.", "We arrived at our destination at midnight."] },
            { word: "Itinerary", phonetic: "/aɪˈtɪnərəri/", meaning: "A planned route or journey.", hindi: "यात्रा कार्यक्रम", examples: ["Here is the itinerary for our trip.", "The tour operator changed the itinerary."] },
            { word: "Spectacular", phonetic: "/spekˈtækjələ(r)/", meaning: "Very exciting to look at.", hindi: "शानदार", examples: ["The view from the top was spectacular.", "A spectacular sunset."] },
            { word: "Traditional", phonetic: "/trəˈdɪʃənl/", meaning: "Existing for a long time.", hindi: "पारंपरिक", examples: ["He wears traditional Indian clothes.", "Traditional music of the region."] },
            { word: "Adventure", phonetic: "/ədˈventʃə(r)/", meaning: "An unusual and exciting experience.", hindi: "साहस", examples: ["Life is a great adventure.", "They went on an adventure in the woods."] },
            { word: "Baggage", phonetic: "/ˈbæɡɪdʒ/", meaning: "Suitcases and bags containing possessions.", hindi: "सामान", examples: ["Check your baggage at the counter.", "Excess baggage fees may apply."] },
            { word: "Cruise", phonetic: "/kruːz/", meaning: "A voyage on a ship or boat for pleasure.", hindi: "समुद्री सैर", examples: ["They went on a Mediterranean cruise.", "A luxury cruise ship."] },
            { word: "Depart", phonetic: "/dɪˈpɑːt/", meaning: "To leave, especially on a journey.", hindi: "प्रस्थान करना", examples: ["The plane departs at 10 AM.", "Train departures are on the screen."] },
            { word: "Expedition", phonetic: "/ˌekspəˈdɪʃn/", meaning: "A journey by a group of people for a purpose.", hindi: "खोजी यात्रा / अभियान", examples: ["An expedition to the North Pole.", "The mountain expedition was successful."] },
            { word: "Flight", phonetic: "/flaɪt/", meaning: "The action of flying through the air.", hindi: "उड़ान", examples: ["I have a flight to Delhi.", "The flight was delayed by two hours."] },
            { word: "Guide", phonetic: "/ɡaɪd/", meaning: "A person who shows the way to others.", hindi: "मार्गदर्शक", examples: ["The tour guide was very helpful.", "Use a guidebook for information."] },
            { word: "Hospitality", phonetic: "/ˌhɒspɪˈtæləti/", meaning: "Friendly reception of guests.", hindi: "सत्कार / मेहमाननवाज़ी", examples: ["Thank you for your hospitality.", "The hotel is known for its hospitality."] },
            { word: "Island", phonetic: "/ˈaɪlənd/", meaning: "A piece of land surrounded by water.", hindi: "द्वीप", examples: ["They live on a small island.", "Mauritius is a beautiful island."] },
            { word: "Journey", phonetic: "/ˈdʒɜːni/", meaning: "The act of traveling from one place to another.", hindi: "यात्रा", examples: ["Have a safe journey!", "A long and tiring journey."] },
            { word: "Landmark", phonetic: "/ˈlændmɑːk/", meaning: "An object or feature that is easily seen.", hindi: "सीमाचिह्न / प्रमुख स्थान", examples: ["The Eiffel Tower is a famous landmark.", "The old church is a local landmark."] },
            { word: "Monument", phonetic: "/ˈmɒnjumənt/", meaning: "A statue or building for a person or event.", hindi: "स्मारक", examples: ["Taj Mahal is a great monument.", "A monument to the soldiers."] },
            { word: "Navigator", phonetic: "/ˈnævɪɡeɪtə(r)/", meaning: "A person who directs the course of a ship.", hindi: "नाविक / दिशा दिखाने वाला", examples: ["He is a skilled navigator.", "Use a navigator for the route."] },
            { word: "Overseas", phonetic: "/ˌəʊvəˈsiːz/", meaning: "Beyond or across the sea.", hindi: "विदेश", examples: ["He is working overseas.", "Overseas travel is exciting."] },
            { word: "Passport", phonetic: "/ˈpɑːspɔːt/", meaning: "A document for international travel.", hindi: "पासपोर्ट / पारपत्र", examples: ["Don't forget your passport.", "Check your passport validity."] },
            { word: "Queue", phonetic: "/kjuː/", meaning: "A line of people waiting.", hindi: "कतार", examples: ["There was a long queue at the airport.", "Wait in the queue for your turn."] },
            { word: "Reservation", phonetic: "/ˌrezəˈveɪʃn/", meaning: "A booking for something.", hindi: "आरक्षण", examples: ["Make a flight reservation early.", "I have a reservation at the hotel."] },
            { word: "Souvenir", phonetic: "/ˌsuːvəˈnɪə(r)/", meaning: "A thing kept as a reminder of a place.", hindi: "निशानी / यादगार", examples: ["Buy a souvenir from the shop.", "This keychain is a souvenir from Paris."] },
            { word: "Tourist", phonetic: "/ˈtʊərɪst/", meaning: "A person who is visiting a place.", hindi: "पर्यटक", examples: ["The city attracts many tourists.", "Tourist attractions were crowded."] },
            { word: "Vacation", phonetic: "/vəˈkeɪʃn/", meaning: "An extended period of recreation.", hindi: "छुट्टियां", examples: ["We are going on vacation.", "Summer vacation is starting."] }
        ]
    },
    {
        id: "business",
        category: "Business & Professional",
        icon: "💼",
        description: "Professional vocabulary for workplace success.",
        words: [
            { word: "Collaborate", phonetic: "/kəˈlæbəreɪt/", meaning: "To work together with others.", hindi: "सहयोग करना", examples: ["The two companies collaborated on the project.", "Let's collaborate on this task."], synonyms: ["Cooperate", "Team up"], antonyms: ["Compete", "Conflict"] },
            { word: "Efficient", phonetic: "/ɪˈfɪʃnt/", meaning: "Working well without wasting time.", hindi: "कुशल / कार्यक्षम", examples: ["She is a very efficient worker.", "The new system is much more efficient."], synonyms: ["Productive", "Organized"], antonyms: ["Inefficient", "Wasteful"] },
            { word: "Implementation", phonetic: "/ˌɪmplɪmenˈteɪʃn/", meaning: "The process of putting a plan into effect.", hindi: "कार्यान्वयन", examples: ["The implementation of the new policy.", "We need to plan the implementation."], synonyms: ["Execution", "Application"] },
            { word: "Negotiate", phonetic: "/nɪˈɡəʊʃieɪt/", meaning: "To try to reach an agreement.", hindi: "मोलभाव करना / बातचीत करना", examples: ["They are negotiating a new deal.", "I managed to negotiate a better price."], synonyms: ["Bargain", "Mediate"] },
            { word: "Strategy", phonetic: "/ˈstrætədʒi/", meaning: "A plan of action to achieve something.", hindi: "रणनीति", examples: ["We need a new marketing strategy.", "The business has a clear strategy for growth."], synonyms: ["Plan", "Tactics"] },
            { word: "Agenda", phonetic: "/əˈdʒendə/", meaning: "A list of items to be discussed at a meeting.", hindi: "कार्यसूची", examples: ["What's on the agenda for today's meeting?", "The chairman set the agenda."] },
            { word: "Bankruptcy", phonetic: "/ˈbæŋkrʌptsi/", meaning: "Legal status of a person who cannot repay debts.", hindi: "दिवालियापन", examples: ["The company filed for bankruptcy.", "Economic crisis led to many bankruptcies."] },
            { word: "Client", phonetic: "/ˈklaɪənt/", meaning: "A person or organization using the services of a professional.", hindi: "ग्राहक", examples: ["We have a meeting with a new client.", "The lawyer represented his client well."] },
            { word: "Deadline", phonetic: "/ˈdedlaɪn/", meaning: "The latest time or date by which something should be completed.", hindi: "समय सीमा", examples: ["The deadline for submission is Friday.", "We are working hard to meet the deadline."] },
            { word: "Entrepreneur", phonetic: "/ˌɒntrəprəˈnɜː(r)/", meaning: "A person who sets up a business, taking financial risks.", hindi: "उद्यमी", examples: ["He is a successful tech entrepreneur.", "Being an entrepreneur requires risk."] },
            { word: "Feedback", phonetic: "/ˈfiːdbæk/", meaning: "Information about reactions to a product or task.", hindi: "प्रतिक्रिया", examples: ["We value our customers' feedback.", "Positive feedback boosts morale."] },
            { word: "Growth", phonetic: "/ɡrəʊθ/", meaning: "The process of increasing in size or importance.", hindi: "विकास / वृद्धि", examples: ["The company has seen steady growth.", "Personal growth is important."] },
            { word: "Incentive", phonetic: "/ɪnˈsentɪv/", meaning: "A thing that motivates or encourages someone.", hindi: "प्रोत्साहन", examples: ["The government offers tax incentives.", "Bonus is a good incentive for workers."] },
            { word: "Job Security", phonetic: "/dʒɒb sɪˈkjʊərəti/", meaning: "The probability that an individual will keep their job.", hindi: "नौकरी की सुरक्षा", examples: ["In this economy, job security is rare.", "Public sector jobs offer better security."] },
            { word: "Knowledgeable", phonetic: "/ˈnɒlɪdʒəbl/", meaning: "Intelligent and well informed.", hindi: "जानकार", examples: ["He is very knowledgeable about the industry.", "Seek advice from a knowledgeable person."] },
            { word: "Liability", phonetic: "/ˌlaɪəˈbɪləti/", meaning: "The state of being held legally responsible.", hindi: "दायित्व", examples: ["The company accepts full liability.", "Know your legal liabilities."] },
            { word: "Marketing", phonetic: "/ˈmɑːkɪtɪŋ/", meaning: "Action of promoting and selling products.", hindi: "विपणन / मार्केटिंग", examples: ["Marketing is key to business success.", "They have a clever marketing campaign."] },
            { word: "Objective", phonetic: "/əbˈdʒektɪv/", meaning: "A thing aimed at or sought; a goal.", hindi: "उद्देश्य", examples: ["What's your primary objective?", "Our main objective is customer satisfaction."] },
            { word: "Profit", phonetic: "/ˈprɒfɪt/", meaning: "Financial gain received from a business.", hindi: "लाभ", examples: ["The company made a huge profit last year.", "Net profit has increased."] },
            { word: "Quota", phonetic: "/ˈkwəʊtə/", meaning: "A fixed share of something that a person is entitled to.", hindi: "कोटा / नियत हिस्सा", examples: ["He met his sales quota for the month.", "The government set import quotas."] },
            { word: "Recruitment", phonetic: "/rɪˈkruːtmənt/", meaning: "The action of finding new people to join a company.", hindi: "भर्ती", examples: ["Recruitment process can be long.", "A specialized recruitment agency."] },
            { word: "Structure", phonetic: "/ˈstrʌktʃə(r)/", meaning: "The arrangement of parts or elements of something complex.", hindi: "संरचना", examples: ["The corporate structure is hierarchical.", "Organizational structure matters."] },
            { word: "Turnover", phonetic: "/ˈtɜːnəʊvə(r)/", meaning: "The amount of money taken by a business in a period.", hindi: "कारोबार / टर्नओवर", examples: ["The annual turnover is $2 million.", "Employee turnover rate is high."] },
            { word: "Unanimous", phonetic: "/juˈnænɪməs/", meaning: "Fully in agreement.", hindi: "एकमत / सर्वसम्मत", examples: ["The board was unanimous in its decision.", "It was a unanimous vote."] },
            { word: "Venture", phonetic: "/ˈventʃə(r)/", meaning: "A risky or daring journey or undertaking.", hindi: "उद्यम", examples: ["They started a new joint venture.", "A business venture in a foreign country."] }
        ]
    },
    {
        id: "phrasal-verbs",
        category: "Common Phrasal Verbs",
        icon: "🔗",
        description: "Dynamic word combinations used by native speakers.",
        words: [
            { word: "Bring up", phonetic: "/brɪŋ ʌp/", meaning: "To mention a subject.", hindi: "चर्चा करना / मुद्दा उठाना", examples: ["Don't bring up that topic again.", "She brought up some interesting points."] },
            { word: "Call off", phonetic: "/kɔːl ɒf/", meaning: "To cancel something.", hindi: "रद्द करना", examples: ["They called off the wedding.", "The meeting was called off."] },
            { word: "Look forward to", phonetic: "/lʊk ˈfɔːwəd tuː/", meaning: "To feel excited about something future.", hindi: "उत्सुकता से प्रतीक्षा करना", examples: ["I look forward to meeting you.", "Children look forward to holidays."] },
            { word: "Set up", phonetic: "/set ʌp/", meaning: "To start or establish something.", hindi: "स्थापित करना", examples: ["He set up his own business.", "We need to set up the equipment."] },
            { word: "Take over", phonetic: "/teɪk ˈəʊvə(r)/", meaning: "To take control of something.", hindi: "नियंत्रण में लेना", examples: ["The company was taken over by a rival.", "Who will take over when he retires?"] },
            { word: "Back out", phonetic: "/bæk aʊt/", meaning: "To withdraw from a commitment.", hindi: "पीछे हटना", examples: ["He backed out of the deal at the last minute.", "You can't back out now."] },
            { word: "Break down", phonetic: "/breɪk daʊn/", meaning: "To stop functioning (machinery).", hindi: "खराब होना", examples: ["My car broke down on the highway.", "The negotiation broke down."] },
            { word: "Carry on", phonetic: "/ˈkæri ɒn/", meaning: "To continue doing something.", hindi: "जारी रखना", examples: ["Please carry on with your work.", "They carried on as if nothing happened."] },
            { word: "Check out", phonetic: "/tʃek aʊt/", meaning: "To examine or investigate.", hindi: "जांच करना / देखना", examples: ["Check out this new website.", "We need to check out the hotel."] },
            { word: "Drop off", phonetic: "/drɒp ɒf/", meaning: "To take someone to a place and leave them there.", hindi: "छोड़ना (कहीं पहुँचाना)", examples: ["I'll drop you off at the station.", "Can you drop off this package?"] },
            { word: "End up", phonetic: "/end ʌp/", meaning: "To eventually reach a state or place.", hindi: "अंततः पहुँचना / होना", examples: ["We ended up getting lost.", "How did you end up here?"] },
            { word: "Fall apart", phonetic: "/fɔːl əˈpɑːt/", meaning: "To break into pieces or fail.", hindi: "बिखर जाना / टूटना", examples: ["The old book is falling apart.", "Their marriage fell apart."] },
            { word: "Get along", phonetic: "/ɡet əˈlɒŋ/", meaning: "To have a friendly relationship.", hindi: "अच्छे संबंध होना", examples: ["Do you get along with your boss?", "The siblings don't get along."] },
            { word: "Hold on", phonetic: "/həʊld ɒn/", meaning: "To wait for a short time.", hindi: "इंतज़ार करना / रुकना", examples: ["Hold on a second, please.", "She told me to hold on."] },
            { word: "Keep up", phonetic: "/kiːp ʌp/", meaning: "To move or develop at the same rate.", hindi: "बराबरी बनाए रखना", examples: ["Technology is moving so fast it's hard to keep up.", "Keep up the good work!"] },
            { word: "Let down", phonetic: "/let daʊn/", meaning: "To disappoint someone.", hindi: "निराश करना", examples: ["I won't let you down.", "He felt let down by his friends."] },
            { word: "Make up", phonetic: "/meɪk ʌp/", meaning: "To invent a story or excuse.", hindi: "बनाना (मनगढ़ंत) / मेल-मिलाप", examples: ["He made up a story about being late.", "They finally made up after the fight."] },
            { word: "Pass out", phonetic: "/pɑːs aʊt/", meaning: "To become unconscious.", hindi: "बेहोश होना", examples: ["It was so hot that he passed out.", "She passed out from exhaustion."] },
            { word: "Run out of", phonetic: "/rʌn aʊt əv/", meaning: "To finish the supply of something.", hindi: "खत्म होना", examples: ["We've run out of milk.", "I'm running out of patience."] },
            { word: "Show off", phonetic: "/ʃəʊ ɒf/", meaning: "To display proudly to impress others.", hindi: "दिखावा करना", examples: ["He likes to show off his new car.", "Stop showing off!"] },
            { word: "Turn down", phonetic: "/tɜːn daʊn/", meaning: "To reject or refuse.", hindi: "अस्वीकार करना / मना करना", examples: ["She turned down the job offer.", "He turned down the music."] },
            { word: "Use up", phonetic: "/juːz ʌp/", meaning: "To consume completely.", hindi: "खत्म कर देना (इस्तेमाल करके)", examples: ["We've used up all the sugar.", "Don't use up all your energy."] },
            { word: "Work out", phonetic: "/wɜːk aʊt/", meaning: "To exercise or solve a problem.", hindi: "व्यायाम करना / हल निकालना", examples: ["I work out at the gym.", "Things will work out in the end."] },
            { word: "Zip up", phonetic: "/zɪp ʌp/", meaning: "To close using a zipper.", hindi: "ज़िप बंद करना", examples: ["Zip up your jacket, it's cold.", "Can you help me zip up this dress?"] },
            { word: "Back down", phonetic: "/bæk daʊn/", meaning: "To admit defeat or stop a claim.", hindi: "पीछे हटना / हार मानना", examples: ["Neither side was willing to back down.", "He finally backed down."] }
        ]
    },
    {
        id: "health",
        category: "Health & Wellness",
        icon: "🧘",
        description: "Vocabulary related to physical and mental well-being.",
        words: [
            { word: "Symptoms", phonetic: "/ˈsɪmptəmz/", meaning: "Signs of physical or mental problems.", hindi: "लक्षण", examples: ["Common symptoms of flu include fever and cough.", "He ignored the early symptoms."] },
            { word: "Nutritious", phonetic: "/njuˈtrɪʃəs/", meaning: "Food that is good for your health.", hindi: "पौष्टिक", examples: ["Fruits and vegetables are highly nutritious.", "I try to eat a nutritious breakfast."] },
            { word: "Hydration", phonetic: "/haɪˈdreɪʃn/", meaning: "Maintaining adequate water in the body.", hindi: "जलयोजन / पानी की पर्याप्त मात्रा", examples: ["Proper hydration is essential for athletes.", "Drink plenty of water to stay hydrated."] },
            { word: "Physical", phonetic: "/ˈfɪzɪkl/", meaning: "Relating to the body rather than the mind.", hindi: "शारीरिक", examples: ["Exercise is important for physical health.", "A physical exam is required."] },
            { word: "Wellness", phonetic: "/ˈwelnəs/", meaning: "The state of being in good health.", hindi: "स्वस्थ अवस्था / खुशहाली", examples: ["The center focuses on holistic wellness.", "Mental wellness is as important as physical health."] },
            { word: "Antibiotics", phonetic: "/ˌæntibaɪˈɒtɪks/", meaning: "Medicine that destroys or slows down growth of bacteria.", hindi: "एंटीबायोटिक्स / जीवाणुरोधी", examples: ["The doctor prescribed antibiotics.", "Complete the course of antibiotics."] },
            { word: "Balanced Diet", phonetic: "/ˌbælənst ˈdaɪət/", meaning: "A diet that contains right amounts of all nutrients.", hindi: "संतुलित आहार", examples: ["Maintain a balanced diet for good health.", "Vegetables are a part of a balanced diet."] },
            { word: "Checkup", phonetic: "/ˈtʃekʌp/", meaning: "A thorough medical examination.", hindi: "जांच / मेडिकल चेकअप", examples: ["I go for a regular medical checkup.", "He had a full physical checkup."] },
            { word: "Digestion", phonetic: "/daɪˈdʒestʃən/", meaning: "Process of breaking down food in the body.", hindi: "पाचन", examples: ["Fiber helps improve digestion.", "Slow digestion can cause bloating."] },
            { word: "Exercise", phonetic: "/ˈeksəsaɪz/", meaning: "Physical activity to stay fit.", hindi: "व्यायाम / कसरत", examples: ["Daily exercise is necessary.", "What's your favorite type of exercise?"] },
            { word: "Fatigue", phonetic: "/fəˈtiːɡ/", meaning: "Extreme tiredness resulting from mental or physical exertion.", hindi: "थकान / क्लान्ति", examples: ["Muscular fatigue after a workout.", "Combat fatigue with proper rest."] },
            { word: "General Anesthesia", phonetic: "/ˌdʒenrəl ˌænəsˈθiːziə/", meaning: "State of total unconsciousness.", hindi: "सामान्य एनेस्थीसिया (बेहोशी)", examples: ["The surgery was done under general anesthesia.", "Feeling groggy after anesthesia."] },
            { word: "Hereditary", phonetic: "/hɪˈredɪtri/", meaning: "Passed on from parents to children.", hindi: "वंशानुगत / आनुवंशिक", examples: ["This condition is hereditary.", "Eye color is a hereditary trait."] },
            { word: "Immunity", phonetic: "/ɪˈmjuːnəti/", meaning: "Ability of the body to resist infection.", hindi: "रोग प्रतिरोधक क्षमता", examples: ["Vitamin C boosts your immunity.", "Natural immunity after recovery."] },
            { word: "Joint Pain", phonetic: "/dʒɔɪnt peɪn/", meaning: "Discomfort at any joint.", hindi: "जोड़ों का दर्द", examples: ["Elderly people often suffer from joint pain.", "Gentle stretches can relieve joint pain."] },
            { word: "Kinesiology", phonetic: "/kaɪˌniːziˈɒlədʒi/", meaning: "Study of the mechanics of body movements.", hindi: "काइनेसियोलॉजी (गति-विज्ञान)", examples: ["He is studying kinesiology.", "Professional athletes often consult kinesiology experts."] },
            { word: "Lifestyle", phonetic: "/ˈlaɪfstaɪl/", meaning: "The way in which a person lives.", hindi: "जीवन शैली", examples: ["Adopt a healthy lifestyle.", " sedentary lifestyle is bad for heart."] },
            { word: "Metabolism", phonetic: "/məˈtæbəlɪzəm/", meaning: "Chemical processes in a living organism to maintain life.", hindi: "चयापचय", examples: ["Exercise can speed up your metabolism.", "Age affects metabolism rate."] },
            { word: "Nutrient", phonetic: "/ˈnjuːtriənt/", meaning: "Substance that provides nourishment.", hindi: "पोषक तत्व", examples: ["Fruits are rich in vital nutrients.", "Absorb nutrients from food."] },
            { word: "Obesity", phonetic: "/əʊˈbiːsəti/", meaning: "State of being grossly fat or overweight.", hindi: "मोटापा", examples: ["Obesity is a major health concern.", "Rising rates of childhood obesity."] },
            { word: "Precaution", phonetic: "/prɪˈkɔːʃn/", meaning: "Action taken in advance to prevent something dangerous.", hindi: "एहतियात / सावधानी", examples: ["Take precautions against sun exposure.", "Safety precautions are necessary."] },
            { word: "Recovery", phonetic: "/rɪˈkʌvəri/", meaning: "Return to a normal state of health.", hindi: "स्वस्थ होना / सुधार", examples: ["Wishing you a speedy recovery.", "The patient made a full recovery."] },
            { word: "Stethoscope", phonetic: "/ˈsteθəskəʊp/", meaning: "Instrument for listening to heart or lungs.", hindi: "स्टेथोस्कोप", examples: ["The doctor used a stethoscope.", "Listening to heartbeat with a stethoscope."] },
            { word: "Therapy", phonetic: "/ˈθerəpi/", meaning: "Treatment intended to relieve or heal a disorder.", hindi: "थेरेपी / चिकित्सा", examples: ["Physical therapy helped her walk again.", "Group therapy for anxiety."] },
            { word: "Ultrasound", phonetic: "/ˈʌltrəsaʊnd/", meaning: "Sound or other vibrations used in medical imaging.", hindi: "अल्ट्रासाउंड", examples: ["The patient had an ultrasound scan.", "Checking the baby with ultrasound."] }
        ]
    },
    {
        id: "food",
        category: "Food & Dining",
        icon: "🍽️",
        description: "Taste the world with restaurant and cooking vocabulary.",
        words: [
            { word: "Cuisine", phonetic: "/kwɪˈziːn/", meaning: "A style or method of cooking from a region.", hindi: "पाक-प्रणाली / व्यंजन शैली", examples: ["I love traditional Italian cuisine.", "Indian cuisine is famous for its spices."] },
            { word: "Delicious", phonetic: "/dɪˈlɪʃəs/", meaning: "Highly pleasant to the taste.", hindi: "स्वादिष्ट", examples: ["That cake was absolutely delicious!", "A delicious meal was served."] },
            { word: "Ingredients", phonetic: "/ɪnˈɡriːdiənts/", meaning: "Food items used to make a dish.", hindi: "सामग्री / घटक", examples: ["What are the ingredients for this soup?", "Always use fresh ingredients."] },
            { word: "Reservation", phonetic: "/ˌrezəˈveɪʃn/", meaning: "Booking a table or room in advance.", hindi: "आरक्षण", examples: ["I’d like to make a reservation for two.", "Did you make a reservation at the restaurant?"] },
            { word: "Vegetarian", phonetic: "/ˌvedʒəˈteəriən/", meaning: "A person who does not eat meat.", hindi: "शाकाहारी", examples: ["Are there any vegetarian options?", "She has been a vegetarian for five years."] },
            { word: "Appetizer", phonetic: "/ˈæpɪtaɪzə(r)/", meaning: "A small dish served before the main meal.", hindi: "क्षुधावर्धक / नाश्ता", examples: ["We ordered some appetizers for the table.", "Bruschetta is a great appetizer."] },
            { word: "Beverage", phonetic: "/ˈbevərɪdʒ/", meaning: "A drink of any type.", hindi: "पेय पदार्थ", examples: ["What kind of beverages do you have?", "Coffee and tea are popular beverages."] },
            { word: "Cater", phonetic: "/ˈkeɪtə(r)/", meaning: "To provide food and drink for a social event.", hindi: "भोजन प्रबंध करना", examples: ["The company caters for large parties.", "Who is catering the wedding?"] },
            { word: "Dessert", phonetic: "/dɪˈzɜːt/", meaning: "The sweet course eaten at the end of a meal.", hindi: "मिठाई / मीठा व्यंजन", examples: ["We had chocolate cake for dessert.", "Fruit salad is a light dessert."] },
            { word: "Entree", phonetic: "/ˈɒntreɪ/", meaning: "The main dish of a meal.", hindi: "मुख्य भोजन", examples: ["The entrees include grilled salmon and steak.", "What's the entree of the day?"] },
            { word: "Flavor", phonetic: "/ˈfleɪvə(r)/", meaning: "The distinctive quality of a food or drink.", hindi: "स्वाद / सुगंध", examples: ["This soup has a rich flavor.", "Add spices to enhance the flavor."] },
            { word: "Garnish", phonetic: "/ˈɡɑːnɪʃ/", meaning: "Small amount of food used to decorate a larger dish.", hindi: "सजावट (भोजन की)", examples: ["Garnish the pasta with fresh parsley.", "A lemon wedge is a common garnish."] },
            { word: "Homemade", phonetic: "/ˌhəʊmˈmeɪd/", meaning: "Made at home rather than in a shop or factory.", hindi: "घर का बना हुआ", examples: ["Nothing beats homemade apple pie.", "She brought some homemade bread."] },
            { word: "Infuse", phonetic: "/ɪnˈfjuːz/", meaning: "To soak in liquid to extract the flavor.", hindi: "मिलाना / भिगोकर स्वाद निकालना", examples: ["The tea is infused with mint.", "Infuse the oil with garlic and herbs."] },
            { word: "Juicy", phonetic: "/ˈdʒuːsi/", meaning: "Containing a lot of juice; succulent.", hindi: "रसीला", examples: ["This peach is so sweet and juicy.", "A juicy burger cooked to perfection."] },
            { word: "Kitchenette", phonetic: "/ˌkɪtʃɪˈnet/", meaning: "A small kitchen or part of a room used as a kitchen.", hindi: "छोटा किचन", examples: ["The hotel room has a small kitchenette.", "Cooking in the kitchenette was easy."] },
            { word: "Lactose-free", phonetic: "/ˈlæktəʊs friː/", meaning: "Not containing lactose (sugar in milk).", hindi: "लैक्टोज रहित", examples: ["I need lactose-free milk for my coffee.", "Is this cheese lactose-free?"] },
            { word: "Marinate", phonetic: "/ˈmærɪneɪt/", meaning: "To soak food in a seasoned liquid before cooking.", hindi: "मसालों में लपेट कर रखना", examples: ["Marinate the chicken overnight.", "The meat was marinated in wine and herbs."] },
            { word: "Nutrient-dense", phonetic: "/ˈnjuːtriənt dens/", meaning: "Food that is high in nutrients but relatively low in calories.", hindi: "पोषक तत्वों से भरपूर", examples: ["Spinach is a nutrient-dense vegetable.", "Choose nutrient-dense snacks."] },
            { word: "Organic", phonetic: "/ɔːˈɡænɪk/", meaning: "Produced without the use of chemical fertilizers.", hindi: "जैविक / ऑर्गेनिक", examples: ["Organic food is becoming more popular.", "She buys only organic vegetables."] },
            { word: "Pastry", phonetic: "/ˈpeɪstri/", meaning: "Dough made from flour, fat, and water.", hindi: "पेस्ट्री", examples: ["She is an expert at making light pastry.", "A selection of French pastries."] },
            { word: "Recipe", phonetic: "/ˈresəpi/", meaning: "A set of instructions for preparing a dish.", hindi: "व्यंजन विधि / रेसिपी", examples: ["Follow the recipe carefully.", "I'm looking for a simple bread recipe."] },
            { word: "Seasoning", phonetic: "/ˈsiːznɪŋ/", meaning: "Salt, herbs, or spices added to food to enhance flavor.", hindi: "तड़का / मसाला", examples: ["Adjust the seasoning with more salt.", "Perfectly balanced seasoning."] },
            { word: "Tableware", phonetic: "/ˈteɪblweə(r)/", meaning: "Dishes, utensils, and glassware used at a table.", hindi: "मेज के बर्तन", examples: ["Elegant tableware for the dinner party.", "Set the tableware carefully."] },
            { word: "Umami", phonetic: "/uˈmɑːmi/", meaning: "A savory taste, one of the five basic tastes.", hindi: "उमामी (स्वादिष्ट/नमकीन स्वाद)", examples: ["Soy sauce has a strong umami flavor.", "Mushrooms are rich in umami."] }
        ]
    },
    {
        id: "technology",
        category: "Technology & Digital",
        icon: "💻",
        description: "Modern terms for the digital era.",
        words: [
            { word: "Algorithm", phonetic: "/ˈælɡərɪðəm/", meaning: "A set of rules for solving problems.", hindi: "कलन विधि / नियम प्रणाली", examples: ["Search engines use complex algorithms.", "The algorithm suggests videos you might like."] },
            { word: "Cybersecurity", phonetic: "/ˌsaɪbə sɪˈkjʊərəti/", meaning: "Protection against digital attacks.", hindi: "साइबर सुरक्षा", examples: ["The company is investing in cybersecurity.", "Keep your passwords strong for better cybersecurity."] },
            { word: "Interface", phonetic: "/ˈɪntəfeɪs/", meaning: "The point where a user interacts with a computer.", hindi: "इंटरफ़ेस", examples: ["The app has a very simple interface.", "A user-friendly interface makes the site easy to navigate."] },
            { word: "Software", phonetic: "/ˈsɒftweə(r)/", meaning: "Computer programs and applications.", hindi: "सॉफ्टवेयर", examples: ["New software was installed today.", "I work in software development."] },
            { word: "Wireless", phonetic: "/ˈwaɪələs/", meaning: "Using radio waves instead of wires.", hindi: "वायरलेस / बेतार", examples: ["The office has wireless internet.", "I use wireless headphones."] },
            { word: "Artificial Intelligence", phonetic: "/ˌɑːtɪfɪʃl ɪnˈtelɪɡəns/", meaning: "Simulation of human intelligence by machines.", hindi: "कृत्रिम बुद्धिमत्ता", examples: ["AI is transforming the medical industry.", "Generative AI can write code."] },
            { word: "Bandwidth", phonetic: "/ˈbændwɪdθ/", meaning: "Range of frequencies within a given band.", hindi: "बैंडविड्थ", examples: ["We need more bandwidth for the video stream.", "Low bandwidth can cause lag."] },
            { word: "Cloud Computing", phonetic: "/klaʊd kəmˈpjuːtɪŋ/", meaning: "Using remote servers hosted on the internet to store data.", hindi: "क्लाउड कंप्यूटिंग", examples: ["AWS is a leading cloud computing service.", "Store your photos in the cloud."] },
            { word: "Data Encryption", phonetic: "/ˈdeɪtə ɪnˈkrɪpʃn/", meaning: "Process of converting data into code to prevent unauthorized access.", hindi: "डेटा एन्क्रिप्शन", examples: ["Data encryption is vital for online banking.", "End-to-end encryption for messages."] },
            { word: "E-commerce", phonetic: "/ˈiː ˌkɒmɜːs/", meaning: "Buying and selling of goods/services over the internet.", hindi: "ई-कॉमर्स / ऑनलाइन व्यापार", examples: ["Amazon is an e-commerce giant.", "E-commerce sales have grown."] },
            { word: "Firewall", phonetic: "/ˈfaɪəwɔːl/", meaning: "Security system designed to block unauthorized access to a network.", hindi: "फ़ायरवॉल", examples: ["The firewall blocked the suspicious traffic.", "Configure the firewall rules."] },
            { word: "Gigabyte", phonetic: "/ˈɡɪɡəbaɪt/", meaning: "Unit of digital information equal to one billion bytes.", hindi: "गीगाबाइट (GB)", examples: ["This file is two gigabytes in size.", "How many gigabytes of RAM do you have?"] },
            { word: "Hardware", phonetic: "/ˈhɑːdweə(r)/", meaning: "Physical components of a computer.", hindi: "हार्डवेयर", examples: ["Hardware repairs can be expensive.", "Install the new hardware drivers."] },
            { word: "Installation", phonetic: "/ˌɪnstəˈleɪʃn/", meaning: "Action of installing something.", hindi: "स्थापना / इंस्टॉलेशन", examples: ["The installation of the new OS is complete.", "Installation Guide is provided."] },
            { word: "Javascript", phonetic: "/ˈdʒɑːvəskrɪpt/", meaning: "A popular programming language for web pages.", hindi: "जावास्क्रिप्ट", examples: ["Javascript is used for frontend development.", "Learn Javascript for web design."] },
            { word: "Keywords", phonetic: "/ˈkiːwɜːdz/", meaning: "Words or phrases used to find information on the web.", hindi: "कीवर्ड्स", examples: ["Use relevant keywords for SEO.", "Enter keywords in the search bar."] },
            { word: "Latency", phonetic: "/ˈleɪtənsi/", meaning: "Delay before a transfer of data begins.", hindi: "विलंबता / लैटेन्सी", examples: ["High latency is bad for online gaming.", "Optimize the network to reduce latency."] },
            { word: "Malware", phonetic: "/ˈmælweə(r)/", meaning: "Software intended to damage or disable computers.", hindi: "मैलवेयर / हानिकारक सॉफ्टवेयर", examples: ["A malware attack on the server.", "Install an anti-malware tool."] },
            { word: "Networking", phonetic: "/ˈnetwɜːkɪŋ/", meaning: "Linked computers to share resources.", hindi: "नेटवर्किंग", examples: ["Computer networking is a vast field.", "Setting up a local area network."] },
            { word: "Open Source", phonetic: "/ˌəʊpən ˈsɔːs/", meaning: "Software for which the original source code is made freely available.", hindi: "ओपन सोर्स", examples: ["Linux is an open source operating system.", "Contribute to open source projects."] },
            { word: "Programming", phonetic: "/ˈprəʊɡræmɪŋ/", meaning: "Process of writing computer programs.", hindi: "प्रोग्रामिंग", examples: ["Programming requires logical thinking.", "He is learning Python programming."] },
            { word: "Quantum Computing", phonetic: "/ˈkwɒntəm kəmˈpjuːtɪŋ/", meaning: "Using quantum-mechanical phenomena.", hindi: "क्वांटम कंप्यूटिंग", examples: ["Quantum computing will solve complex problems.", "The future of quantum computing."] },
            { word: "Resolution", phonetic: "/ˌrezəˈluːʃn/", meaning: "Detail an image holds.", hindi: "रिज़ॉल्यूशन / स्पष्टता", examples: ["This monitor has 4K resolution.", "Higher resolution means better image quality."] },
            { word: "Smartphone", phonetic: "/ˈsmɑːtfəʊn/", meaning: "A mobile phone that performs many functions of a computer.", hindi: "स्मार्टफोन", examples: ["I use my smartphone for everything.", "New smartphone models are launched."] },
            { word: "Virtual Reality", phonetic: "/ˌvɜːtʃuəl riˈæləti/", meaning: "Computer-generated simulation of a 3D environment.", hindi: "वर्चुअल रियलिटी (आभासी वास्तविकता)", examples: ["VR gaming is very immersive.", "Experience virtual reality with a headset."] }
        ]
    },
    {
        id: "education",
        category: "Education & Learning",
        icon: "🎓",
        description: "Academic terms for students and scholars.",
        words: [
            { word: "Academic", phonetic: "/ˌækəˈdemɪk/", meaning: "Relating to education and scholarship.", hindi: "शैक्षिक / अकादमिक", examples: ["He has a brilliant academic record.", "Academic freedom is important."] },
            { word: "Curriculum", phonetic: "/kəˈrɪkjələm/", meaning: "The subjects comprising a course of study.", hindi: "पाठ्यक्रम", examples: ["The school is designing a new curriculum.", "Mathematics is part of the core curriculum."] },
            { word: "Graduate", phonetic: "/ˈɡrædʒueɪt/", meaning: "A person who has successfully completed a course of study.", hindi: "स्नातक", examples: ["He is a graduate of Harvard University.", "Latest graduates are looking for jobs."] },
            { word: "Scholarship", phonetic: "/ˈskɒləʃɪp/", meaning: "A grant or payment made to support a student.", hindi: "छात्रवृत्ति", examples: ["She won a scholarship to study abroad.", "Apply for a merit-based scholarship."] },
            { word: "Tutor", phonetic: "/ˈtjuːtə(r)/", meaning: "A private teacher, typically one who teaches a single pupil.", hindi: "निजी शिक्षक / ट्यूटर", examples: ["He hired a math tutor for his son.", "University tutors provide guidance."] },
            { word: "Assignment", phonetic: "/əˈsaɪnmənt/", meaning: "A task or piece of work allocated to someone.", hindi: "कार्य / असाइनमेंट", examples: ["Submit your assignment by Monday.", "She is working on a difficult assignment."] },
            { word: "Bachelor's Degree", phonetic: "/ˌbætʃələz dɪˈɡriː/", meaning: "An undergraduate academic degree.", hindi: "स्नातक की उपाधि", examples: ["He received his Bachelor's degree last year.", "Typical course for a Bachelor's degree."] },
            { word: "Certification", phonetic: "/ˌsɜːtɪfɪˈkeɪʃn/", meaning: "A document that proves you have skills.", hindi: "प्रमाणन", examples: ["You need a certification to teach.", "Professional certification enhances your resume."] },
            { word: "Diploma", phonetic: "/dɪˈpləʊmə/", meaning: "A certificate awarded by a school/college.", hindi: "डिप्लोमा", examples: ["She has a diploma in graphic design.", "High school diploma is mandatory."] },
            { word: "Exposition", phonetic: "/ˌekspəˈzɪʃn/", meaning: "A comprehensive description and explanation of an idea.", hindi: "व्याख्या / प्रदर्शनी", examples: ["A clear exposition of the theory.", "The student gave a brilliant exposition."] },
            { word: "Foundation", phonetic: "/faʊnˈdeɪʃn/", meaning: "An underlying basis or principle.", hindi: "बुनियाद / आधार", examples: ["The course provides a solid foundation in math.", "Laying the foundation for future studies."] },
            { word: "Hypothesis", phonetic: "/haɪˈpɒθəsɪs/", meaning: "A proposed explanation made on limited evidence.", hindi: "परिकल्पना", examples: ["Testing the hypothesis with experiments.", "The research supports his hypothesis."] },
            { word: "Institution", phonetic: "/ˌɪnstɪˈtjuːʃn/", meaning: "An organization founded for a religious or educational purpose.", hindi: "संस्थान", examples: ["A prestigious educational institution.", "The bank is a financial institution."] },
            { word: "Journal", phonetic: "/ˈdʒɜːnl/", meaning: "A newspaper or magazine that deals with a particular subject.", hindi: "पत्रिका / जर्नल", examples: ["His article was published in a medical journal.", "Keep a daily journal."] },
            { word: "Knowledge", phonetic: "/ˈnɒlɪdʒ/", meaning: "Facts, information, and skills acquired through experience.", hindi: "ज्ञान", examples: ["She has extensive knowledge of history.", "Knowledge is power."] },
            { word: "Lecture", phonetic: "/ˈlektʃə(r)/", meaning: "An educational talk to an audience.", hindi: "व्याख्यान / लेक्चर", examples: ["The professor gave a lecture on economics.", "Attend the guest lecture."] },
            { word: "Master's Degree", phonetic: "/ˌmɑːstəz dɪˈɡriː/", meaning: "A postgraduate academic degree.", hindi: "परास्नातक की उपाधि", examples: ["She has a Master's degree in psychology.", "Applying for a Master's program."] },
            { word: "Notation", phonetic: "/nəʊˈteɪʃn/", meaning: "A series of signs or symbols used to represent something.", hindi: "अंकन / संकेत लिपि", examples: ["Musical notation is complex.", "Mathematical notation for numbers."] },
            { word: "Objective", phonetic: "/əbˈdʒektɪv/", meaning: "A thing aimed at or sought; a goal.", hindi: "लक्ष्य / उद्देश्य", examples: ["What's the objective of this lesson?", "Clearly defined learning objectives."] },
            { word: "Pedagogy", phonetic: "/ˈpedəɡɒdʒi/", meaning: "The method and practice of teaching.", hindi: "शिक्षाशास्त्र", examples: ["Innovative pedagogy in modern schools.", "Study of pedagogy is important for teachers."] },
            { word: "Questionnaire", phonetic: "/ˌkwestʃəˈneə(r)/", meaning: "A set of printed or written questions.", hindi: "प्रश्नावली", examples: ["Fill out the questionnaire.", "A research questionnaire for students."] },
            { word: "Recitation", phonetic: "/ˌresɪˈteɪʃn/", meaning: "Action of repeating something from memory.", hindi: "पाठ / सस्वर पाठ", examples: ["A poetry recitation competition.", "Daily recitation of prayers."] },
            { word: "Syllabus", phonetic: "/ˈsɪləbəs/", meaning: "Outlines of the subjects in a course of study.", hindi: "पाठ्यक्रम रूपरेखा / सिलेबस", examples: ["Check the syllabus for exam topics.", "The syllabus is quite vast."] },
            { word: "Literacy", phonetic: "/ˈlɪtərəsi/", meaning: "The ability to read and write.", hindi: "साक्षरता", examples: ["The government is working to improve literacy rates.", "Digital literacy is essential today."] },
            { word: "Scholar", phonetic: "/ˈskɒlə(r)/", meaning: "A specialist in a particular branch of study.", hindi: "विद्वान", examples: ["He is a renowned Sanskrit scholar.", "Scholars are debating the new findings."] }
        ]
    },
    {
        id: "nature",
        category: "Nature & Environment",
        icon: "🌿",
        description: "Words to describe the natural world around us.",
        words: [
            { word: "Atmosphere", phonetic: "/ˈætməsfɪə(r)/", meaning: "The envelope of gases surrounding the earth.", hindi: "वायुमंडल / वातावरण", examples: ["The atmosphere is mostly nitrogen.", "Trees help clean the atmosphere."] },
            { word: "Biodiversity", phonetic: "/ˌbaɪəʊdaɪˈvɜːsəti/", meaning: "Variety of plant and animal life.", hindi: "जैव विविधता", examples: ["The rainforest has incredible biodiversity.", "We must protect biodiversity."] },
            { word: "Conservation", phonetic: "/ˌkɒnsəˈveɪʃn/", meaning: "Protection of natural resources.", hindi: "संरक्षण", examples: ["Wildlife conservation is crucial.", "Energy conservation starts at home."] },
            { word: "Phenomenon", phonetic: "/fəˈnɒmɪnən/", meaning: "An observable event or fact.", hindi: "घटना / अद्भुत दृश्य", examples: ["The Northern Lights are a natural phenomenon.", "Global warming is a worrying phenomenon."] },
            { word: "Sustainable", phonetic: "/səˈsteɪnəbl/", meaning: "Able to be maintained over time.", hindi: "सतत / टिकाऊ", examples: ["We need sustainable energy sources.", "Sustainable farming is better for the planet."] },
            { word: "Aquatic", phonetic: "/əˈkwætɪk/", meaning: "Relating to water.", hindi: "जलीय", examples: ["Aquatic animals such as fish and whales.", "The park has many aquatic plants."] },
            { word: "Biosphere", phonetic: "/ˈbaɪəʊsfɪə(r)/", meaning: "The regions of the surface and atmosphere of the earth occupied by living organisms.", hindi: "जीवमंडल", examples: ["Protecting the Earth's biosphere.", "The complex interactions within the biosphere."] },
            { word: "Climate Change", phonetic: "/ˈklaɪmət tʃeɪndʒ/", meaning: "A change in global or regional climate patterns.", hindi: "जलवायु परिवर्तन", examples: ["Climate change is a global crisis.", "Reducing carbon emissions to fight climate change."] },
            { word: "Deforestation", phonetic: "/ˌdiːˌfɒrɪˈsteɪʃn/", meaning: "Action of clearing a wide area of trees.", hindi: "वनों की कटाई", examples: ["Deforestation leads to habitat loss.", "Stop illegal deforestation in the Amazon."] },
            { word: "Ecosystem", phonetic: "/ˈiːkəʊsɪstəm/", meaning: "A biological community of interacting organisms and their physical environment.", hindi: "पारिस्थितिकी तंत्र", examples: ["Tidal pools are fragile ecosystems.", "The balance of the ecosystem is delicate."] },
            { word: "Flora and Fauna", phonetic: "/ˈflɔːrə ənd ˈfɔːnə/", meaning: "Plants and animals of a particular region.", hindi: "वनस्पति और जीव", examples: ["The local flora and fauna are unique.", "Protecting the mountain's flora and fauna."] },
            { word: "Geology", phonetic: "/dʒiˈɒlədʒi/", meaning: "Science that deals with the earth's physical structure.", hindi: "भूविज्ञान", examples: ["Studying the geology of the Grand Canyon.", "A fascinating book on geology."] },
            { word: "Habitat", phonetic: "/ˈhæbɪtæt/", meaning: "Natural home or environment of an animal/plant.", hindi: "प्राकृतिक वास / आवास", examples: ["The bird's natural habitat is the rainforest.", "Destruction of polar bear habitat."] },
            { word: "Invertebrate", phonetic: "/ɪnˈvɜːtɪbrət/", meaning: "An animal lacking a backbone.", hindi: "अकशेरुकी (बिना रीढ़ वाला)", examples: ["Insects and spiders are invertebrates.", "Study of invertebrate biology."] },
            { word: "Jungle", phonetic: "/ˈdʒʌŋɡl/", meaning: "An area of land overgrown with dense forest.", hindi: "जंगल", examples: ["The explorers were lost in the jungle.", "A thick tropical jungle."] },
            { word: "Kinetic Energy", phonetic: "/kaɪˈnetɪk ˈenədʒi/", meaning: "Energy which a body possesses by virtue of being in motion.", hindi: "गतिज ऊर्जा", examples: ["Wind turbines convert kinetic energy to electricity.", "High kinetic energy of the particles."] },
            { word: "Landscape", phonetic: "/ˈlændskeɪp/", meaning: "All the visible features of an area of countryside or land.", hindi: "परिदृश्य / लैंडस्केप", examples: ["The snowy landscape was beautiful.", "A rugged mountain landscape."] },
            { word: "Meteorology", phonetic: "/ˌmiːtiəˈrɒlədʒi/", meaning: "Science dealing with the atmosphere and its phenomena.", hindi: "मौसम विज्ञान", examples: ["Meteorology helps in predicting the weather.", "He is an expert in meteorology."] },
            { word: "Natural Resource", phonetic: "/ˈnætʃrəl rɪˈsɔːs/", meaning: "Materials or substances occurring in nature.", hindi: "प्राकृतिक संसाधन", examples: ["Water is a precious natural resource.", "Conservation of natural resources."] },
            { word: "Ozone Layer", phonetic: "/ˈəʊzəʊn ˈleɪə(r)/", meaning: "Layer in the earth's stratosphere that absorbs ultraviolet radiation.", hindi: "ओजोन परत", examples: ["The ozone layer protects us from UV rays.", "Depletion of the ozone layer is a concern."] },
            { word: "Pollution", phonetic: "/pəˈluːʃn/", meaning: "Presence of harmful or poisonous substances in the environment.", hindi: "प्रदूषण", examples: ["Air pollution is a major health risk.", "Reduce plastic pollution in our oceans."] },
            { word: "Quarry", phonetic: "/ˈkwɒri/", meaning: "A place, typically a large, deep pit, from which stone or other materials are or have been extracted.", hindi: "खदान / पत्थर की खान", examples: ["The old stone quarry is now a park.", "Limestone from the local quarry."] },
            { word: "Reptile", phonetic: "/ˈreptaɪl/", meaning: "A vertebrate animal of a class that includes snakes, lizards, turtles, and crocodiles.", hindi: "सरीसृप", examples: ["Snakes are common reptiles.", "A reptile house at the zoo."] },
            { word: "Solar Energy", phonetic: "/ˈsəʊlə(r) ˈenədʒi/", meaning: "Radiant light and heat from the Sun that is harnessed.", hindi: "सौर ऊर्जा", examples: ["Investing in solar energy for the home.", "Solar energy is a clean resource."] },
            { word: "Terrain", phonetic: "/təˈreɪn/", meaning: "A stretch of land, especially with regard to its physical features.", hindi: "भूभाग / इलाका", examples: ["The difficult mountain terrain made hiking hard.", "Rugged desert terrain."] }
        ]
    },
    {
        id: "idioms",
        category: "Idioms & Phrases",
        icon: "🗣️",
        description: "Common expressions used in daily conversation.",
        words: [
            { word: "Piece of cake", phonetic: "/piːs əv keɪk/", meaning: "Something that is very easy to do.", hindi: "बहुत आसान काम (बाएं हाथ का खेल)", examples: ["The exam was a piece of cake.", "Fixing this is a piece of cake for him."] },
            { word: "Under the weather", phonetic: "/ˈʌndə(r) ðə ˈweðə(r)/", meaning: "Feeling slightly unwell or sick.", hindi: "तबीयत खराब होना", examples: ["I’m feeling a bit under the weather today.", "He stayed home because he was under the weather."] },
            { word: "Break the ice", phonetic: "/breɪk ðə aɪs/", meaning: "To start a conversation in a social setting.", hindi: "बातचीत शुरू करना / झिझक मिटाना", examples: ["He told a joke to break the ice.", "Let's play a game to break the ice."] },
            { word: "Ball is in your court", phonetic: "/bɔːl ɪz ɪn jɔː(r) kɔːt/", meaning: "It is your turn to make a decision.", hindi: "अब फैसला आपके हाथ में है", examples: ["I’ve made my offer, now the ball is in your court.", "The ball is in her court now."] },
            { word: "Arm and a leg", phonetic: "/ɑːm ənd ə leɡ/", meaning: "To be extremely expensive.", hindi: "बहुत महंगा होना", examples: ["This car cost me an arm and a leg.", "College tuition can cost an arm and a leg."] },
            { word: "Bite the bullet", phonetic: "/baɪt ðə ˈbʊlɪt/", meaning: "To accept something difficult or unpleasant.", hindi: "मजबूरी में कठिन परिस्थिति का सामना करना", examples: ["I hate going to the dentist, but I'll just have to bite the bullet.", "Bite the bullet and finish the work."] },
            { word: "Call it a day", phonetic: "/kɔːl ɪt ə deɪ/", meaning: "To stop working on something.", hindi: "आज का काम खत्म करना", examples: ["We're all tired, let's call it a day.", "I think we should call it a day and go home."] },
            { word: "Cut to the chase", phonetic: "/kʌt tuː ðə tʃeɪs/", meaning: "To get to the point without wasting time.", hindi: "मुद्दे पर आना", examples: ["Stop talking about the weather and cut to the chase.", "I'll cut to the chase: we need more money."] },
            { word: "Hit the nail on the head", phonetic: "/hɪt ðə neɪl ɒn ðə hed/", meaning: "To describe exactly what is causing a situation.", hindi: "बिल्कुल सही बात कहना", examples: ["You hit the nail on the head with that analysis.", "She hit the nail on the head when she said he was lazy."] },
            { word: "Let the cat out of the bag", phonetic: "/let ðə kæt aʊt əv ðə bæɡ/", meaning: "To accidentally reveal a secret.", hindi: "अनजाने में राज खोल देना", examples: ["I accidentally let the cat out of the bag about the surprise party.", "Who let the cat out of the bag?"] },
            { word: "Miss the boat", phonetic: "/mɪs ðə bəʊt/", meaning: "To be too late to take advantage of an opportunity.", hindi: "मौका गंवा देना", examples: ["If you don't buy the tickets now, you'll miss the boat.", "He missed the boat on that investment."] },
            { word: "Once in a blue moon", phonetic: "/wʌns ɪn ə bluː muːn/", meaning: "Something that happens very rarely.", hindi: "कभी-कभार (ईद का चाँद)", examples: ["I go to the cinema once in a blue moon.", "He calls us once in a blue moon."] },
            { word: "Pull someone's leg", phonetic: "/pʊl ˈsʌmwʌnz leɡ/", meaning: "To joke with someone by saying something true.", hindi: "मज़ाक करना / टांग खींचना", examples: ["Is it really your birthday, or are you pulling my leg?", "Stop pulling my leg!"] },
            { word: "See eye to eye", phonetic: "/siː aɪ tuː aɪ/", meaning: "To agree with someone fully.", hindi: "पूर्णतः सहमत होना", examples: ["My brother and I don't see eye to eye on politics.", "They finally see eye to eye on the project."] },
            { word: "Spill the beans", phonetic: "/spɪl ðə biːnz/", meaning: "To give away a secret on purpose.", hindi: "राज उगल देना", examples: ["Tell me what happened! Spill the beans!", "She spilled the beans about the new plan."] },
            { word: "Take with a grain of salt", phonetic: "/teɪk wɪð ə ɡreɪn əv sɔːlt/", meaning: "To not believe something is completely true.", hindi: "किसी बात पर पूरी तरह यकीन न करना", examples: ["Take his stories with a grain of salt; he tends to exaggerate.", "I take everything he says with a grain of salt."] },
            { word: "Up in the air", phonetic: "/ʌp ɪn ðə eə(r)/", meaning: "Something that is uncertain or not yet decided.", hindi: "अभी कुछ तय नहीं होना / अनिश्चित", examples: ["Our travel plans are still up in the air.", "The future of the company is up in the air."] },
            { word: "Wrap your head around", phonetic: "/ræp jɔː(r) hed əˈraʊnd/", meaning: "To understand something complicated.", hindi: "किसी जटिल बात को समझना", examples: ["I'm trying to wrap my head around this new math formula.", "It took me a while to wrap my head around the concept."] },
            { word: "Barking up the wrong tree", phonetic: "/ˈbɑːkɪŋ ʌp ðə rɒŋ triː/", meaning: "To be looking in the wrong place or accusing the wrong person.", hindi: "गलत दिशा में प्रयास करना / गलत आदमी पर शक करना", examples: ["If you think I took your money, you're barking up the wrong tree.", "The police are barking up the wrong tree."] },
            { word: "Beat around the bush", phonetic: "/biːt əˈraʊnd ðə bʊʃ/", meaning: "To avoid talking about what is important.", hindi: "घुमा-फिराकर बात करना", examples: ["Stop beating around the bush and tell me what you want.", "Don't beat around the bush; get to the point."] },
            { word: "Better late than never", phonetic: "/ˈbetə(r) leɪt ðən ˈnevə(r)/", meaning: "It is better to do something late than not at all.", hindi: "देर आए दुरुस्त आए", examples: ["He finally apologized. Better late than never, I guess.", "I finished the project two days late, but better late than never."] },
            { word: "Break a leg", phonetic: "/breɪk ə leɡ/", meaning: "Good luck (especially for a performance).", hindi: "शुभकामनाएं (खासकर स्टेज पर जाने से पहले)", examples: ["You'll do great in the play tonight. Break a leg!", "Break a leg at your audition!"] },
            { word: "Cost an arm and a leg", phonetic: "/kɒst ən ɑːm ənd ə leɡ/", meaning: "To be extremely expensive.", hindi: "बहुत ज़्यादा महंगा होना", examples: ["That designer handbag cost her an arm and a leg.", "Repairing the roof cost an arm and a leg."] },
            { word: "Cry over spilled milk", phonetic: "/kraɪ ˈəʊvə(r) spɪld mɪlk/", meaning: "To complain about something that already happened and cannot be changed.", hindi: "बीती बातों पर पछताना", examples: ["I know you lost the game, but don't cry over spilled milk.", "There's no use crying over spilled milk."] },
            { word: "Every cloud has a silver lining", phonetic: "/ˈevri klaʊd hæz ə ˈsɪlvə ˈlaɪnɪŋ/", meaning: "Every difficult situation has a positive side.", hindi: "हर मुश्किल के पीछे एक उम्मीद की किरण होती है", examples: ["I lost my job, but I found a better one. Every cloud has a silver lining.", "Every cloud has a silver lining; keep your head up."] }
        ]
    }
];
